I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/tutorial_story.rpy", line 180, in script
    $ inventory.add_data(cathy_phoone)
  File "game/tutorial_story.rpy", line 180, in <module>
    $ inventory.add_data(cathy_phoone)
NameError: name 'cathy_phoone' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/tutorial_story.rpy", line 180, in script
    $ inventory.add_data(cathy_phoone)
  File "/Users/anastasiakozlova/renpy-8.1.3-sdk/renpy/ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/anastasiakozlova/renpy-8.1.3-sdk/renpy/python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/tutorial_story.rpy", line 180, in <module>
    $ inventory.add_data(cathy_phoone)
NameError: name 'cathy_phoone' is not defined

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Thu Jan 11 13:01:07 2024
