I'm sorry, but an uncaught exception occurred.

While running game code:
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\49157\\Downloads\\renpy-8.1.3-sdk\\social-engineering-game\\game\\saves\\persistent'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\main.py", line 684, in main
    renpy.persistent.update(True)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\persistent.py", line 401, in update
    save()
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\persistent.py", line 419, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\savelocation.py", line 545, in save_persistent
    l.save_persistent(data)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\savelocation.py", line 378, in save_persistent
    safe_rename(fn_new, fn)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\loadsave.py", line 302, in safe_rename
    os.unlink(new)
PermissionError: [WinError 32] Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird: 'C:\\Users\\49157\\Downloads\\renpy-8.1.3-sdk\\social-engineering-game\\game\\saves\\persistent'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Thu May 16 21:23:36 2024
