I'm sorry, but an uncaught exception occurred.

After initialization, but before game start.
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\SeAdv\\github\\social-engineering-game\\game\\saves\\navigation.json.new' -> 'C:\\SeAdv\\github\\social-engineering-game\\game\\saves\\navigation.json'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\SeAdv\renpy\renpy-8.1.3-sdk\renpy\bootstrap.py", line 275, in bootstrap
    renpy.main.main()
  File "C:\SeAdv\renpy\renpy-8.1.3-sdk\renpy\main.py", line 620, in main
    renpy.dump.dump(False)
  File "C:\SeAdv\renpy\renpy-8.1.3-sdk\renpy\dump.py", line 262, in dump
    os.rename(new, filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\SeAdv\\github\\social-engineering-game\\game\\saves\\navigation.json.new' -> 'C:\\SeAdv\\github\\social-engineering-game\\game\\saves\\navigation.json'

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Tue Jun  4 16:04:49 2024
