I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level_1.rpy", line 1549, in script
    show Me chef
Exception: Image 'Me' does not accept attributes 'chef'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/level_1.rpy", line 1549, in script
    show Me chef
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1428, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\ast.py", line 1391, in show_imspec
    renpy.config.show(name,
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\exports.py", line 733, in show
    if not base.find_target() and renpy.config.missing_show:
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\display\image.py", line 421, in find_target
    self.target = target._duplicate(a)
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 499, in _duplicate
    args.extraneous()
  File "C:\Users\49157\Downloads\renpy-8.1.3-sdk\renpy\display\core.py", line 362, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'Me' does not accept attributes 'chef'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Sun Feb  4 17:22:28 2024
