I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script call
    call tutorial
  File "game/tutorial_story.rpy", line 21, in script
    p "Yes, it’s my first day here."
Exception: Sayer 'p' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script call
    call tutorial
  File "game/tutorial_story.rpy", line 21, in script
    p "Yes, it’s my first day here."
  File "/Users/anastasiakozlova/renpy-8.1.3-sdk/renpy/ast.py", line 890, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/anastasiakozlova/renpy-8.1.3-sdk/renpy/ast.py", line 783, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'p' is not defined.

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Tue Dec 19 11:50:50 2023
