I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/level_4.rpy", line 50, in script
    $ rules = [
  File "game/level_4.rpy", line 57, in <module>
    ("Password must include the Roman numeral for 99 (answer: X_IX)", lambda pwd: pwd.startswith('YErffej450') and any(c in "!@#$%^&*()-_+=" for c in pwd) and 'keyboard' in pwd.lower() and 'XCIX' in pwd.upper())
TypeError: 'tuple' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/level_4.rpy", line 50, in script
    $ rules = [
  File "C:\SeAdv\renpy\renpy-8.1.3-sdk\renpy\ast.py", line 1138, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\SeAdv\renpy\renpy-8.1.3-sdk\renpy\python.py", line 1122, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/level_4.rpy", line 57, in <module>
    ("Password must include the Roman numeral for 99 (answer: X_IX)", lambda pwd: pwd.startswith('YErffej450') and any(c in "!@#$%^&*()-_+=" for c in pwd) and 'keyboard' in pwd.lower() and 'XCIX' in pwd.upper())
TypeError: 'tuple' object is not callable

Windows-10-10.0.22631 AMD64
Ren'Py 8.1.3.23091805
Social Engineering Game 1.0
Tue Jun 18 12:19:22 2024
